#ifndef QUINTIC_SMOOTHING_SPLINE_1D_HPP
#define QUINTIC_SMOOTHING_SPLINE_1D_HPP

#include "mfem.hpp"
#include "linear_1d_node_data.hpp"

#include <array>
#include <functional>
#include <memory>
#include <vector>

namespace spline
{

struct QuinticSmoothingOptions
{
   /**
    * Parameter p in
    *
    *   p sum_i (S(x_i)-y_i)^2
    *     + (1-p) h_bar^5 integral (S'''(x))^2 dx.
    *
    * Values closer to one follow the data more closely; values closer to
    * zero smooth more strongly. A strict 0 < p < 1 is required.
    */
   mfem::real_t data_fidelity = 0.5;
   mfem::real_t coordinate_tolerance = 0.0;
};

struct QuinticSmoothingSolveOptions
{
   mfem::real_t relative_tolerance = 1.0e-12;
   mfem::real_t absolute_tolerance = 0.0;
   int maximum_iterations = 1000;
   int krylov_dimension = 100;
   int print_level = 0;
   bool require_convergence = true;
   bool direct_solver = true;
};

struct QuinticSmoothingSolveResult
{
   bool converged = false;
   int iterations = 0;
   mfem::real_t initial_norm = -1.0;
   mfem::real_t final_norm = -1.0;
   bool direct_solver = true;
};

/**
 * Parallel quintic smoothing spline for a scalar P1 H1
 * mfem::ParGridFunction on a conforming one-dimensional mesh.
 *
 * On each interval [a,b], with h_e=b-a,
 *
 *   S_e(x) = sum_{j=0}^5 a_{e,j} ((x-b)/h_e)^j.
 *
 * The spline is C4 across every interior knot. It does not generally
 * interpolate the supplied nodal values. Instead, it minimizes
 *
 *   p sum_i (S(x_i)-y_i)^2
 *     + (1-p) h_bar^5 integral (S'''(x))^2 dx,
 *
 * where h_bar is the average interval length. The h_bar^5 factor makes p
 * dimensionless and keeps the normalized element matrices well scaled.
 * The natural endpoint conditions are generated by the minimization; no
 * finite-difference endpoint derivatives are used.
 *
 * Construction and Solve() are collective on the ParMesh communicator.
 * The input ParGridFunction and its mesh/space must outlive this object.
 */
class ParQuinticSmoothingSpline1D
{
public:
   static constexpr int order = 5;
   static constexpr int coefficients_per_interval = order + 1;

   explicit ParQuinticSmoothingSpline1D(
      const mfem::ParGridFunction &input,
      const QuinticSmoothingOptions &smoothing_options =
         QuinticSmoothingOptions());

   ParQuinticSmoothingSpline1D(
      const ParQuinticSmoothingSpline1D &) = delete;
   ParQuinticSmoothingSpline1D &operator=(
      const ParQuinticSmoothingSpline1D &) = delete;
   ParQuinticSmoothingSpline1D(
      ParQuinticSmoothingSpline1D &&) = delete;
   ParQuinticSmoothingSpline1D &operator=(
      ParQuinticSmoothingSpline1D &&) = delete;
   ~ParQuinticSmoothingSpline1D() = default;

   /// Reassemble the smoothing KKT matrix and reload the input data.
   void Assemble();

   QuinticSmoothingSolveResult Solve(
      const QuinticSmoothingSolveOptions &options =
         QuinticSmoothingSolveOptions());

   /// Full symmetric-indefinite KKT matrix.
   const mfem::HypreParMatrix &SystemMatrix() const;

   /**
    * Matrix B in b=B y, with y in distributed true-DOF ordering. For an
    * adjoint satisfying A^T lambda=q, grad_y S(x)=B^T lambda.
    */
   const mfem::HypreParMatrix &RightHandSideDataJacobian() const;
   const mfem::HypreParVector &RightHandSide() const;
   const mfem::HypreParVector &CoefficientVector() const;

   mfem::real_t DataFidelity() const { return data_fidelity_; }

   /**
    * Collectively replace y without rebuilding or refactorizing the system.
    * local_true_y uses the input space's locally owned true-DOF ordering.
    */
   void SetDataValues(const mfem::Vector &local_true_y);

   /// Compatibility spelling matching the interpolating-spline classes.
   void SetInterpolationValues(const mfem::Vector &local_true_y)
   {
      SetDataValues(local_true_y);
   }

   /// Reload y from the ParGridFunction supplied to the constructor.
   void RefreshDataValues();

   void RefreshInterpolationValues() { RefreshDataValues(); }

   HYPRE_BigInt GlobalNumberOfIntervals() const
   {
      return global_number_of_intervals_;
   }

   int LocalNumberOfIntervals() const
   {
      return static_cast<int>(intervals_.size());
   }

   std::array<mfem::real_t, coefficients_per_interval>
   LocalCoefficients(int local_element) const;

   mfem::real_t EvaluateLocalElement(int local_element,
                                     mfem::real_t x, int d = 0) const;

   bool TryEvaluateLocal(mfem::real_t x, mfem::real_t &value,
                         int d = 0) const;

   /** Collectively evaluate S or one of its derivatives on every rank. */
   mfem::real_t Evaluate(mfem::real_t x, int d = 0) const;

   const std::vector<mfem::real_t> &LocalNodeCoordinates() const
   {
      return node_data_.Coordinates();
   }

   mfem::Vector EvaluateDisplacedNodes(
      const mfem::Vector &displacements) const;

   mfem::Vector Evaluate(const mfem::Vector &evaluation_points,
                         int d = 0) const;

   /**
    * Collectively return the locally owned portion of grad_y S(x). A direct
    * solve must have been completed so the retained MUMPS factorization can
    * perform the transpose solve.
    */
   mfem::Vector EvaluateDataGradient(mfem::real_t x) const;

private:
   struct Neighbor
   {
      HYPRE_BigInt global_interval = -1;
      mfem::real_t x_left = 0.0;
      mfem::real_t x_right = 0.0;

      bool IsSet() const { return global_interval >= 0; }
   };

   struct Interval
   {
      int local_element = -1;
      int left_vertex = -1;
      int right_vertex = -1;
      HYPRE_BigInt global_interval = -1;

      mfem::real_t x_left = 0.0;
      mfem::real_t x_right = 0.0;
      HYPRE_BigInt left_global_true_dof = -1;
      HYPRE_BigInt right_global_true_dof = -1;

      Neighbor left_neighbor;
      Neighbor right_neighbor;
      bool physical_left_boundary = false;
      bool physical_right_boundary = false;
   };

   struct RowEntry
   {
      HYPRE_BigInt column = -1;
      mfem::real_t value = 0.0;
   };

   const mfem::ParGridFunction *input_ = nullptr;
   mfem::ParFiniteElementSpace *input_space_ = nullptr;
   mfem::ParMesh *mesh_ = nullptr;
   MPI_Comm comm_ = MPI_COMM_NULL;
   int rank_ = -1;

   mfem::real_t data_fidelity_ = 0.5;
   mfem::real_t coordinate_tolerance_ = 0.0;
   ParLinear1DNodeData node_data_;

   std::vector<Interval> intervals_;
   mfem::Array<HYPRE_BigInt> coefficient_offsets_;
   mfem::Array<HYPRE_BigInt> constraint_offsets_;
   mfem::Array<HYPRE_BigInt> system_offsets_;
   HYPRE_BigInt global_number_of_intervals_ = 0;
   HYPRE_BigInt global_coefficient_size_ = 0;
   mfem::real_t global_x_left_ = 0.0;
   mfem::real_t global_x_right_ = 0.0;

   std::unique_ptr<mfem::HypreParMatrix> A_;
   std::unique_ptr<mfem::HypreParMatrix> rhs_data_jacobian_;
   std::unique_ptr<mfem::HypreParVector> rhs_;
   std::unique_ptr<mfem::HypreParVector> system_solution_;
   std::unique_ptr<mfem::HypreParVector> coefficients_;
   std::unique_ptr<mfem::Solver> direct_solver_;
   bool solved_ = false;

   void BuildIntervals();
   void CompleteOffRankNeighbors();
   void AssembleSmoothingSystem();

   static void BuildCSR(std::vector<std::vector<RowEntry>> &rows,
                        std::vector<int> &I,
                        std::vector<HYPRE_BigInt> &J,
                        std::vector<mfem::real_t> &data);

   bool Near(mfem::real_t a, mfem::real_t b) const;
   static mfem::real_t IntegerPower(mfem::real_t x, int exponent);
   static mfem::real_t FallingFactorial(int j, int derivative);
   static HYPRE_BigInt CoefficientColumn(HYPRE_BigInt global_interval,
                                         int j);

   void AddEntry(std::vector<RowEntry> &row,
                 HYPRE_BigInt global_interval,
                 int coefficient,
                 mfem::real_t value) const;

   void AddDerivative(std::vector<RowEntry> &row,
                      HYPRE_BigInt global_interval,
                      mfem::real_t x_right,
                      mfem::real_t interval_length,
                      mfem::real_t x,
                      int derivative,
                      mfem::real_t row_scale) const;
};

} // namespace spline

#endif // QUINTIC_SMOOTHING_SPLINE_1D_HPP
